### ISSUE TITLE
Incorrect links to Source control and bug tracker in plugins db entry

### ISSUE THREAD

**Issue by danmarsden** [angelitro/moodle-block_statics#1]
the links to source control and bug tracker in your plugins db entry point to:
https://github.com/angelitro/moodle-block_statics.git

the source control url should be:
https://github.com/angelitro/moodle-block_statics

the tracker should be:
https://github.com/angelitro/moodle-block_statics/issues

**Comment by angelitro** [comment]
fixed up !
