### ISSUE TITLE
consider using recordsets

### ISSUE THREAD

**Issue by danmarsden** [angelitro/moodle-block_statics#12]
get_records** style functions obtain all records from the db and store in PHP memory - when dealing with large data-sets (like the files table which could be massive) it would be better for you to use "recordset" style functions (just make sure you also "close" the recordset when you are finished with it.

More info on recordsets is available here:
https://docs.moodle.org/dev/Data_manipulation_API#Using_Recordsets

**Comment by angelitro** [comment]
I changed to 'recorset' where I could.
