### ISSUE TITLE
Consider plugin type being used

### ISSUE THREAD

**Issue by danmarsden** [angelitro/moodle-block_statics#16]
The link < Go > displayed in the block isn't very tidy - it would be better to display something like "Statics report" - but I also wonder if this plugin should actually be a block? - maybe it should be a report or local plugin and override the course navigation menu to add a link to the same place as other course reports?

It's fine if you want to keep this as a block - but you will definitely need to improve the existing "< Go >" string.

**Comment by angelitro** [comment]
You're right, I like "statics report", but would like to keep this as a block.
