### ISSUE TITLE
thirdpartylibs.xml

### ISSUE THREAD

**Issue by danmarsden** [angelitro/moodle-block_statics#17]
This is really just informational because you really need to completely remove the bootstrap code from your plugin and instead use the core bootstrap code in Moodle core.

But... when including 3rd party code within your plugin you must add a thirdpartylibs.xml file that describes the 3rd party lib and the details on the license in use.
more info here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

Hopefully you can just close this as won't fix, because you will have just removed the bootstrap libs.

**Comment by angelitro** [comment]
I include thirdpartylibs.xml file describes bootstrap library because only loads in Moodle versions before 3.2. 
I hope that's right.

**Comment by danmarsden** [comment]
That's fine for plugin approval. 

My "personal" preference is to create multiple branches when there is a requirement for code like this - it helps to decrease technical debt in the longer-term (3.1 is only supported for another 4 months and then all sites running older versions should be upgrading their core release rather than installing extra plugins like yours.)

Using multiple branches means you are able to keep a much cleaner code-base and you don't want to keep these sorts of things in your code forever - you will eventually want to drop support for older versions.

But - there's even some resistance to that internally here at Catalyst - some devs prefer to maintain a single codebase that supports all supported Moodle versions.

btw - feel free to close these issues when you have resolved them.

**Comment by angelitro** [comment]
thanks for your tips!!!
