### ISSUE TITLE
css in styles.css not specific enough

### ISSUE THREAD

**Issue by danmarsden** [angelitro/moodle-block_statics#2]
all custom css added by the pluigin should be very specific - typically content will only be displayed within the block so you should be able to prefix all css with:
.block_statics
eg:
```
.block_statics .cont {
```
Please also review your use of the bootstrap css - Moodle 3.2 and higher should already include bootstrap 4 and you should rely on the core bootstrap css instead of adding it on your own.

**Comment by angelitro** [comment]
All css begin with block_statics.
Only loads the bootstrap library in Moodle versions before 3.2
