### ISSUE TITLE
Code precheck issues.

### ISSUE THREAD

**Issue by danmarsden** [angelitro/moodle-block_statics#3]
The moodle.org plugins db reports a number of coding violations that would be good for you to review.
You can see the report by going here:
https://moodle.org/plugins/pluginversions.php?plugin=block_statics

and clicking on the "code prechecks" icon to see the full report.

**Comment by danmarsden** [comment]
Please note - not all failures in that report will be blockers for approval in the plugins db, but fixing them makes it much easier for us to review your code.

**Comment by angelitro** [comment]
almost all coding violations solved.
