### ISSUE TITLE
consider removal of "db/events.php"

### ISSUE THREAD

**Issue by danmarsden** [angelitro/moodle-block_statics#6]
you don't seem to implement any custom event handling and events.php is not a required file so it would be better for you to remove this file rather than including an empty file. Ideally this file should only be there if you actually implement custom event handling.

The upgrade.php file could stay there, but you aren't doing anything in it and it's not a required file, so I'd probably delete that too to make for a cleaner code-base.

**Comment by angelitro** [comment]
events.php and upgrade.php removed.
