### ISSUE TITLE
get_content is always called twice

### ISSUE THREAD

**Issue by danmarsden** [angelitro/moodle-block_statics#7]
the get_content function is called twice for each block on every page load.

For this reason you need to build $this->content the first time the function is called, and then the 2nd time it is called you need to check if it is not empty and return it. That way you're not running all that code twice on every page load.

See the example here:
https://github.com/moodle/moodle/blob/master/blocks/html/block_html.php#L56

**Comment by angelitro** [comment]
fixed up, added 'if' appropriate.
