### ISSUE TITLE
un-necessary get_record call.

### ISSUE THREAD

**Issue by danmarsden** [angelitro/moodle-block_statics#8]
the get_record('course') here:
https://github.com/angelitro/moodle-block_statics/blob/master/block_statics.php#L61

is not required, the global $COURSE var will already contain the full Course record - and at this stage (inside a block) you will always get a valid $COURSE global so you don't need to check to see if it is a valid course. You should avoid making unnecessary DB calls as these are "expensive" and impact on page load performance.

**Comment by angelitro** [comment]
fixed up, this get_record erased
