### ISSUE TITLE
normally local functions are stored within locallib.php in root

### ISSUE THREAD

**Issue by danmarsden** [angelitro/moodle-block_statics#9]
normal practice is for local plugin functions to go into a "locallib.php" file in the root of the plugin - not within a lib.php file in a "lib" folder - it might be nice to make this more like a normal moodle plugin by moving your lib/lib.php file into a /locallib.php file.

This is not a blocker for approval - just a comment on normal moodle coding guidelines - feel free to close as won't fix.

**Comment by angelitro** [comment]
fixed up, lib/lib.php file into a /locallib.php file.
